# Generated by Django 4.1.2 on 2023-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveCamera', '0002_uploadimage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
