# Generated by Django 4.1.2 on 2023-10-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='category',
            field=models.CharField(max_length=200, null=True, verbose_name='カテゴリ'),
        ),
    ]
