# Generated by Django 4.1.2 on 2023-11-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='user_id'),
        ),
    ]
