# Generated by Django 4.1.2 on 2023-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_post_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='user_id'),
        ),
    ]
