# Generated by Django 4.1.2 on 2023-11-21 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0003_alter_post_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDSR_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('index', models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='index')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='index'),
        ),
    ]
