# Generated by Django 4.1.2 on 2023-11-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0004_hdsr_model_alter_post_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdsr_model',
            name='score',
            field=models.IntegerField(default=0, verbose_name='スコア'),
        ),
        migrations.AlterField(
            model_name='hdsr_model',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='発話'),
        ),
    ]
