# Generated by Django 4.1.2 on 2023-12-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0005_hdsr_model_score_alter_hdsr_model_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('old', models.IntegerField(default=0, verbose_name='年齢')),
                ('sex', models.CharField(max_length=200, verbose_name='性別')),
                ('birth', models.DateTimeField(verbose_name='生年月日')),
                ('place', models.CharField(max_length=200, verbose_name='場所')),
                ('high_score', models.IntegerField(default=0, verbose_name='最高スコア')),
                ('row_score', models.IntegerField(default=0, verbose_name='最低スコア')),
                ('hdsr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dialog.hdsr_model', verbose_name='HDS-R')),
            ],
        ),
    ]
