# Generated by Django 4.1.2 on 2023-12-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0006_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='birth',
            field=models.DateField(verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='hdsr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dialog.hdsr_model', verbose_name='HDS-R'),
        ),
    ]
