# Generated by Django 4.1.2 on 2023-12-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0007_alter_userdata_birth_alter_userdata_hdsr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='hdsr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dialog.hdsr_model', verbose_name='HDS-R'),
        ),
    ]
