# Generated by Django 4.1.2 on 2023-12-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0008_alter_userdata_hdsr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='old',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sex',
            field=models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別'),
        ),
    ]
