# Generated by Django 4.1.2 on 2023-12-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0009_rename_old_userdata_age_alter_userdata_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='hdsr',
        ),
        migrations.AddField(
            model_name='userdata',
            name='hdsr',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='dialog.hdsr_model', verbose_name='HDS-R'),
        ),
    ]
