# Generated by Django 4.1.2 on 2023-12-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0012_rename_high_score_userdata_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdsr_model',
            name='index',
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='age_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='backwards1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2、8、6の逆唱'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='backwards1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='backwards2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3、5、2、9の逆唱'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='backwards2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='math1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='100引く7'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='math1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='math2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='93引く7'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='math2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='居場所'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='place_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='recite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='三つの言葉の暗唱'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='recite_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='repeat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='三つの言葉の復唱'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='repeat_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='today',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='年月日曜日'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='today_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='vege',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='知っている野菜'),
        ),
        migrations.AddField(
            model_name='hdsr_model',
            name='vege_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdsr_model',
            name='score',
            field=models.IntegerField(default=-1, verbose_name='スコア総和'),
        ),
        migrations.AlterField(
            model_name='post',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialog.hdsr_model', verbose_name='index'),
        ),
    ]
