# Generated by Django 4.1.2 on 2023-12-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0013_remove_hdsr_model_index_hdsr_model_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdsr_model',
            name='asigned',
            field=models.BooleanField(default=False, help_text='割り当てられていればTrue'),
        ),
    ]
