# Generated by Django 4.1.2 on 2023-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='redate',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
