# Generated by Django 4.1.2 on 2023-10-27 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_alter_post_redate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 28), verbose_name='日付'),
        ),
    ]
