# Generated by Django 4.1.2 on 2023-10-27 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='post',
            name='redate',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
