# Generated by Django 4.1.2 on 2023-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date_alter_post_redate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=200, null=True, verbose_name='カテゴリ'),
        ),
    ]
